[package]
name = "cap_98549"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
capability_common = { path = "../common" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
